<a href="https://colab.research.google.com/github/princesapkota/worksheet5AI/blob/main/wokrsheet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Problem 1
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/datasets/student.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
# Displaying few rows of the DataFrame
df.head()

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [5]:
# Top 5 rows of the dataset.
print(df.head())

# Bottom  of the dataset.
print(df.tail())

   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62
     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72


In [6]:
# Information of the datasets
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [7]:
# Descriptive information of the dataset.
df.describe()

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [8]:
# Defining x and y as Math and Reading Score
X = df[['Math', 'Reading']]
Y = df['Writing']

print("Features of (X): \n", X)
print("Features of (Y): \n", Y)

Features of (X): 
      Math  Reading
0      48       68
1      62       81
2      79       80
3      76       83
4      59       64
..    ...      ...
995    72       74
996    73       86
997    89       87
998    83       82
999    66       66

[1000 rows x 2 columns]
Features of (Y): 
 0      63
1      72
2      78
3      79
4      62
       ..
995    70
996    90
997    94
998    78
999    72
Name: Writing, Length: 1000, dtype: int64


In [9]:
# Problem 2
from sklearn.linear_model import LinearRegression

# Create a Linear Regression model with no intercept
model = LinearRegression(fit_intercept=False)

# Train the model
model.fit(X, Y)

LinearRegression(fit_intercept=False)

In [10]:
# Define matrix X (features)
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # Shape: (3, 3)

# Define vector W (weights)
W = np.array([0.1, 0.2, 0.3])  # Shape: (3,)

# Calculate Y using Y = W^T X
# Since W is a 1D array, transpose is unnecessary
Y = np.dot(W, X)  # Shape: (3,)

# Print the results
print("Matrix X (features):\n", X)
print("\nVector W (weights):\n", W)
print("\nVector Y (predictions):\n", Y)

Matrix X (features):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector W (weights):
 [0.1 0.2 0.3]

Vector Y (predictions):
 [3.  3.6 4.2]


In [11]:
from sklearn.model_selection import train_test_split

# Split the data into training and test sets (80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)

X_train shape: (2, 3)
X_test shape: (1, 3)
Y_train shape: (2,)
Y_test shape: (1,)


In [12]:
# Split the data into training and test sets (80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)

X_train shape: (2, 3)
X_test shape: (1, 3)
Y_train shape: (2,)
Y_test shape: (1,)


In [13]:
# Features of (X) and (Y)
X = df[['Math', 'Reading']].values
Y = df['Writing'].values

print("Features of (X): \n", X)
print("Features of (Y): \n", Y)

Features of (X): 
 [[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]
Features of (Y): 
 [ 63  72  78  79  62  85  83  41  80  77  64  90  45  77  70  46  76  44
  85  72  53  66  75  49  84  83  68  66  77  78  74  83  72  65  46  66
  50  79  68  46  86  70  61  53  72  75  50  77 100  81 100  87  78  48
  50  44  48  43  67  78  58  91  92  78  42  85  73  83  61  58  60  55
  48  62  68  59  62  48  74  63  80  79  73  79  45  67  89  77  81  88
  53  68  79  77  63  73  60  67 100  79  26  51  80  57  41  78  68  49
  76  41  71  77  89  86  55  80  56  74  85  80  73  74  86  56  53  44
  41  59  71  81  74  78  67  53  56  75  82  79  99  76  59  96  75  61
  56  88  65 100  79  55  61  83  74  59  54  47  82  74  59  74  84  59
  43  65  61  78  84  73  73  92  63  72  61  59  70  87  78  65  73  62
  69  55  73  63  67  86  78  85  83  80  60  90  56  70  55  80  82  60
  78  76  94  75  68  71  85  46  58  46  84  58  57  59  77  63  68  99
  48  91  57  80  46  75  

In [14]:
# Initializing the Weight
W = np.random.rand(X.shape[1], 1)  # Adjust size based on the number of features

# Initialize learning rate and number of iterations
learning_rate = 0.01
num_iterations = 1000

print("Weight matrix (W):\n", W)
print("\nLearning rate:", learning_rate)
print("\nNumber of iterations:", num_iterations)

Weight matrix (W):
 [[0.65535009]
 [0.46968699]]

Learning rate: 0.01

Number of iterations: 1000


In [15]:
def gradient_descent(X, Y, W, learning_rate, num_iterations):
    m = X.shape[1]

    for i in range(num_iterations):
        # Calculate predictions
        Y_predicted = X.T @ W

        # Calculate error
        error = Y_predicted - Y

        # Update weights
        W = W - (learning_rate / m) * (X @ error)

    return W


# Define matrix X (features)
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define target vector Y
Y = np.array([10, 20, 30])

# Initialize weights W
W = np.zeros(X.shape[0])

# Parameters
learning_rate = 0.01
num_iterations = 1000

# Call the gradient descent function to learn the parameters
W = gradient_descent(X, Y, W, learning_rate, num_iterations)

print("Learned weights W:\n", W)


Learned weights W:
 [ 8.1593304   3.28437337 -1.59058366]


In [16]:
from sklearn.metrics import mean_squared_error, r2_score  # Import the required functions

X_test = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
Y_test = np.array([10, 20, 30])

# Use the learned weights W to make predictions
Y_pred = X_test.T @ W

# Calculate RMSE (Root Mean Squared Error)
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))

# Calculate R² (Coefficient of Determination)
r2 = r2_score(Y_test, Y_pred)

# Print the evaluation metrics
print("RMSE:", rmse)
print("R2:", r2)


RMSE: 0.12097088754016638
R2: 0.9997804906655162


In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
